### ISSUE TITLE
Cannot push a change to repo

### ISSUE THREAD

**Issue by EugeneKonneh** [gothinkster/angularjs-realworld-example-app#17]
Pushing Eugene.Konneh
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/gothinkster/angularjs-realworld-example-app.git/': The requested URL returned error: 403
Pushing to https://github.com/gothinkster/angularjs-realworld-example-app.git

**Comment by geromegrignon** [comment]
Hello, you can't directly push a commit to a repository without required access rights.
