### ISSUE TITLE
Hi I am learning your tutorial but I can not download your project on this github

### ISSUE THREAD

**Issue by wangran326990** [gothinkster/angularjs-realworld-example-app#2]
Hi 

I use this command  git clone -b 00-seed git@github.com:gothinkster/productionready-angularjs-client.git to download your project but I got this error

Cloning into 'productionready-angularjs-client'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Best regards 
Ran

**Comment by apai4** [comment]
Hey Ran!

I responded to the email you sent, but for anyone else that comes across this issue:

Make sure you've set up your SSH keys with Github (see [here](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) for instructions)

Or use the HTTPS URL for cloning the repository:

`git clone -b 00-seed https://github.com/gothinkster/productionready-angularjs-client.git`

Cheers,
Albert Pai
