### ISSUE TITLE
Transition issues ahoy

### ISSUE THREAD

**Issue by peterkmurphy** [gothinkster/angularjs-realworld-example-app#4]
This is what is logged to the console when I follow the build instructions. Is it something I can safely ignore?
`Error: transition superseded
$get@http://localhost:4000/main.js:2904:42
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
injectionArgs@http://localhost:4000/main.js:9349:58
invoke@http://localhost:4000/main.js:9375:18
registerDirective/</<@http://localhost:4000/main.js:12484:33
forEach@http://localhost:4000/main.js:4898:11
registerDirective/<@http://localhost:4000/main.js:12482:13
invoke@http://localhost:4000/main.js:9383:16
enforcedReturnValue@http://localhost:4000/main.js:9217:20
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
addDirective@http://localhost:4000/main.js:14341:42
collectDirectives@http://localhost:4000/main.js:13548:13
compileNodes@http://localhost:4000/main.js:13341:22
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compile@http://localhost:4000/main.js:13226:15
bootstrapApply/<@http://localhost:4000/main.js:6384:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4000/main.js:22513:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4000/main.js:22613:20
bootstrapApply@http://localhost:4000/main.js:6382:9
invoke@http://localhost:4000/main.js:9383:16
bootstrap/doBootstrap@http://localhost:4000/main.js:6380:5
bootstrap@http://localhost:4000/main.js:6400:12
[5]<@http://localhost:4000/main.js:38880:1
s@http://localhost:4000/main.js:1:246
e@http://localhost:4000/main.js:1:425
@http://localhost:4000/main.js:1:11
 Possibly unhandled rejection: {} main.js:18869:18

Error: transition prevented
$get@http://localhost:4000/main.js:2905:41
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
injectionArgs@http://localhost:4000/main.js:9349:58
invoke@http://localhost:4000/main.js:9375:18
registerDirective/</<@http://localhost:4000/main.js:12484:33
forEach@http://localhost:4000/main.js:4898:11
registerDirective/<@http://localhost:4000/main.js:12482:13
invoke@http://localhost:4000/main.js:9383:16
enforcedReturnValue@http://localhost:4000/main.js:9217:20
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
addDirective@http://localhost:4000/main.js:14341:42
collectDirectives@http://localhost:4000/main.js:13548:13
compileNodes@http://localhost:4000/main.js:13341:22
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compile@http://localhost:4000/main.js:13226:15
bootstrapApply/<@http://localhost:4000/main.js:6384:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4000/main.js:22513:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4000/main.js:22613:20
bootstrapApply@http://localhost:4000/main.js:6382:9
invoke@http://localhost:4000/main.js:9383:16
bootstrap/doBootstrap@http://localhost:4000/main.js:6380:5
bootstrap@http://localhost:4000/main.js:6400:12
[5]<@http://localhost:4000/main.js:38880:1
s@http://localhost:4000/main.js:1:246
e@http://localhost:4000/main.js:1:425
@http://localhost:4000/main.js:1:11
 Possibly unhandled rejection: {} main.js:18869:18

Error: transition aborted
$get@http://localhost:4000/main.js:2906:39
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
injectionArgs@http://localhost:4000/main.js:9349:58
invoke@http://localhost:4000/main.js:9375:18
registerDirective/</<@http://localhost:4000/main.js:12484:33
forEach@http://localhost:4000/main.js:4898:11
registerDirective/<@http://localhost:4000/main.js:12482:13
invoke@http://localhost:4000/main.js:9383:16
enforcedReturnValue@http://localhost:4000/main.js:9217:20
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
addDirective@http://localhost:4000/main.js:14341:42
collectDirectives@http://localhost:4000/main.js:13548:13
compileNodes@http://localhost:4000/main.js:13341:22
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compile@http://localhost:4000/main.js:13226:15
bootstrapApply/<@http://localhost:4000/main.js:6384:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4000/main.js:22513:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4000/main.js:22613:20
bootstrapApply@http://localhost:4000/main.js:6382:9
invoke@http://localhost:4000/main.js:9383:16
bootstrap/doBootstrap@http://localhost:4000/main.js:6380:5
bootstrap@http://localhost:4000/main.js:6400:12
[5]<@http://localhost:4000/main.js:38880:1
s@http://localhost:4000/main.js:1:246
e@http://localhost:4000/main.js:1:425
@http://localhost:4000/main.js:1:11
 Possibly unhandled rejection: {} main.js:18869:18

Error: transition failed
$get@http://localhost:4000/main.js:2907:38
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
injectionArgs@http://localhost:4000/main.js:9349:58
invoke@http://localhost:4000/main.js:9375:18
registerDirective/</<@http://localhost:4000/main.js:12484:33
forEach@http://localhost:4000/main.js:4898:11
registerDirective/<@http://localhost:4000/main.js:12482:13
invoke@http://localhost:4000/main.js:9383:16
enforcedReturnValue@http://localhost:4000/main.js:9217:20
invoke@http://localhost:4000/main.js:9383:16
createInjector/protoInstanceInjector<@http://localhost:4000/main.js:9177:20
getService@http://localhost:4000/main.js:9324:32
addDirective@http://localhost:4000/main.js:14341:42
collectDirectives@http://localhost:4000/main.js:13548:13
compileNodes@http://localhost:4000/main.js:13341:22
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compileNodes@http://localhost:4000/main.js:13357:15
compile@http://localhost:4000/main.js:13226:15
bootstrapApply/<@http://localhost:4000/main.js:6384:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4000/main.js:22513:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4000/main.js:22613:20
bootstrapApply@http://localhost:4000/main.js:6382:9
invoke@http://localhost:4000/main.js:9383:16
bootstrap/doBootstrap@http://localhost:4000/main.js:6380:5
bootstrap@http://localhost:4000/main.js:6400:12
[5]<@http://localhost:4000/main.js:38880:1
s@http://localhost:4000/main.js:1:246
e@http://localhost:4000/main.js:1:425
@http://localhost:4000/main.js:1:11
 Possibly unhandled rejection: {} main.js:18869:18

Error: this.listConfig is undefined
runQuery@http://localhost:4000/main.js:39306:9
setListTo@http://localhost:4000/main.js:39287:7
ArticleListCtrl@http://localhost:4000/main.js:39267:5
invoke@http://localhost:4000/main.js:9383:16
$controllerInit@http://localhost:4000/main.js:15236:24
nodeLinkFn@http://localhost:4000/main.js:14113:35
compileTemplateUrl/<@http://localhost:4000/main.js:14521:13
processQueue@http://localhost:4000/main.js:21189:37
scheduleProcessQueue/<@http://localhost:4000/main.js:21233:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4000/main.js:22513:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:4000/main.js:22327:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4000/main.js:22621:13
bootstrapApply@http://localhost:4000/main.js:6382:9
invoke@http://localhost:4000/main.js:9383:16
bootstrap/doBootstrap@http://localhost:4000/main.js:6380:5
bootstrap@http://localhost:4000/main.js:6400:12
[5]<@http://localhost:4000/main.js:38880:1
s@http://localhost:4000/main.js:1:246
e@http://localhost:4000/main.js:1:425
@http://localhost:4000/main.js:1:11
 main.js:18869:18`

**Comment by garrethpxy** [comment]
As mentioned in #6, you'll need to use angular 1.5.x. 

`npm uninstall angular@1.6.2`
`npm install angular@1.5.8`

**Comment by peterkmurphy** [comment]
Thank you, garrethpxy. Your instructions seem to have solved that issue nicely. I believe this issue can be closed.

**Comment by ZookeeMedia** [comment]
Yes, this helped me today.
